# =============================================================================
# Ansible Role: WireGuard - Molecule Convergence Playbook
# =============================================================================
# This playbook executes the main role functionality in the test environment.
# It performs the following steps:
# - Updates package repositories
# - Ensures system readiness
# - Executes the WireGuard role with test configuration
#
# Flow:
# 1. Update package cache
# 2. Wait for system initialization
# 3. Apply WireGuard role with minimal test configuration
# =============================================================================

---
# -----------------------------------------------------------------------------
# 1. Pre-Tasks Setup
# -----------------------------------------------------------------------------
- name: molecule | Converge
  hosts: all

  pre_tasks:
    # Package Cache Update
    - name: ðŸ”„ Converge | Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: >
        ansible_os_family == "Debian"

    - name: ðŸ”„ Converge | Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when: >
        ansible_os_family == "RedHat"

    # System Initialization
    - name: â³ Converge | Wait for systemd to complete initialization
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: >
        ansible_facts['service_mgr'] == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

# -----------------------------------------------------------------------------
# 2. Role Execution with Test Variables
# -----------------------------------------------------------------------------
  vars:
    # Test-specific configuration for WireGuard
    wireguard_role_action: "all"
    wireguard_interface: "wg0"
    wireguard_network_base: "10.0.0.0/24"
    wireguard_network_prefix: "10.0.0"
    wireguard_port: 51820
    wireguard_generate_keys: true
    wireguard_enable_logging: true
    wireguard_service_enabled: true
    wireguard_start_service: false  # Don't start service in tests to avoid networking issues
    wireguard_enable_service: false # Don't enable service in tests
    wireguard_inventory_group: "all"
    # Enable molecule test mode to skip multi-host validation
    wireguard_molecule_test_mode: true

  roles:
    - role: grzegorzfranus.wireguard
