# =============================================================================
# Ansible Role: WireGuard - Molecule Preparation Playbook
# =============================================================================
# This playbook prepares the test environment for Molecule testing.
# It performs necessary system preparations before role execution:
# - Fixes file permissions
# - Ensures kernel modules availability
# - Validates system requirements
# - Sets up required dependencies
#
# Flow:
# 1. Fix system file permissions
# 2. Validate kernel capabilities for WireGuard
# 3. Validate system state
# =============================================================================

---
# -----------------------------------------------------------------------------
# 1. System File Permissions & Kernel Setup
# -----------------------------------------------------------------------------
- name: molecule | Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: 🛠️ Prepare | Fix /etc/shadow permissions
      register: etc_shadow
      ansible.builtin.shell:
        cmd: |
          echo "🔍 Checking /etc/shadow permissions..."
          ls -l /etc/shadow
          chmod 0400 /etc/shadow
          echo "✅ Fixed /etc/shadow permissions:"
          ls -l /etc/shadow
          echo ""

    - name: 📊 Prepare | Verify shadow file permissions
      ansible.builtin.debug:
        var: etc_shadow.stdout

    - name: 🔍 Prepare | Check if WireGuard kernel module can be loaded
      ansible.builtin.shell:
        cmd: |
          echo "🧪 Testing WireGuard kernel module availability..."
          # Check if module exists
          if modinfo wireguard >/dev/null 2>&1; then
            echo "✅ WireGuard kernel module is available"
          else
            echo "⚠️ WireGuard kernel module not available (this is expected in containers)"
          fi
          echo ""
      register: wg_module_check

    - name: 📊 Prepare | Show WireGuard module check results
      ansible.builtin.debug:
        var: wg_module_check.stdout

    - name: 🛠️ Prepare | Ensure /etc/wireguard directory permissions
      ansible.builtin.file:
        path: /etc/wireguard
        state: directory
        mode: '0755'
        owner: root
        group: root
      ignore_errors: true  # Directory might not exist yet
